### ISSUE TITLE
Can't load plugin

### ISSUE THREAD

**Issue by mstefaniak10** [uklance/gradle-java-monkey-patch#1]
I do see the plugin listed here

https://plugins.gradle.org/plugin/com.lazan.java-monkey-patch

But when I add this my build.gradle file 

plugins {
    id "com.lazan.java-monkey-patch" version "1.0"
}

I get the error 

Error:Could not find gradle.plugin.com.lazan:java-monkey-patch:1.0.
Searched in the following locations:
    https://plugins.gradle.org/m2/gradle/plugin/com/lazan/java-monkey-patch/1.0/java-monkey-patch-1.0.pom
    https://plugins.gradle.org/m2/gradle/plugin/com/lazan/java-monkey-patch/1.0/java-monkey-patch-1.0.jar
Required by:
    project :

Thanks

**Comment by uklance** [comment]
Looks like [this issue](https://discuss.gradle.org/t/plugin-authors-please-use-the-latest-plugin-publish-plugin-others-may-result-in-a-broken-upload/23573). I just checked and I published with version 0.9.5 of the publishing plugin. I'll need to publish again with 0.9.7+

**Comment by uklance** [comment]
Currently waiting for gradle team to delete the broken plugin
See [here](https://discuss.gradle.org/t/please-delete-plugin-gradle-plugin-com-lazan-java-monkey-patch-1-0/24077)

**Comment by uklance** [comment]
Fixed, please try again now

**Comment by mikestef9** [comment]
Working now thanks
